// Program to show single line comment
/*class Comment
{
	public static void main(String[] args) {
		// Single line comment hare
		System.out.println("Single line comment above.");
		System.out.println("Multi line comments below");
		/*  Comment line 1
			Comment line 2
			Comment line 3 */
//	}
//}

// Program to illustrate frequently used Comment tags
/**
* <h1> Find average of three numbers!</h1>
* The FindAvg program implements an application that
* Simply calculates average of three integers and Prints
* the output on the screen.
* 
* @author Praful Dubey
* @version 12.0
* @since 2021-05-04
*/

public class Comment
{
	/**
	* This method is used to find average of three integers.
	* @param numA This is the first parameter to findAvg method
	* @param numB This is the second parameter to findAvg method
	* @param numC This is the second parameter to findAvg method
	* @return int This returns average of numA, numB and numC.
	*/
	public int findAvg(int numA, int numB, int numC)
	{
		return (numA + numB + numC)/3;
	}

	/**
	* This is the main method which makes use of findAvg method.
	* @param args Unused.
	* @return Nothing
	*/

	public static void main(String[] args) {
		Comment obj = new Comment();
		int avg = obj.findAvg(10, 20, 30);

		System.out.println("Average of 10, 20, and 30 is :" + avg);
	}
}

/*For the above code documentation can be generated by using a tool ‘javadoc’ :
Javadoc can be used by running the following command in terminal.*/

// javadoc Comment.java